export XORGSTD_VIDEO_CARDS="vesa modesetting intel radeon nouveau dummy vmware apm"
export XORGSTD_INPUT_DEVICES="keyboard vmmouse mouse evdev synaptics"
export XORGMIN_VIDEO_CARDS="vesa modesetting nv dummy glint rendition s3 trident sis voodoo sisusb ast apm"
export XORGMIN_INPUT_DEVICES="keyboard mouse evdev synaptics"
export VIDEO_CARDS="${XORGSTD_VIDEO_CARDS}"
export INPUT_DEVICES="${XORGSTD_INPUT_DEVICES}"
export FEATURES="parallel-fetch -collision-protect -protect-owned -xattr"
export MAKEOPTS="-j13"
export PORTAGE_NICENESS="19"
export ACCEPT_KEYWORDS="~x86"
export ACCEPT_LICENSE="*"
export CFLAGS="-Os -march=i686 -mtune=core2 -mmmx -mmmxext -msse -msse2 -msse3 -mssse3 -pipe"
export CXXFLAGS="-Os -march=i686 -mtune=core2 -mmmx -mmmxext -msse -msse2 -msse3 -mssse3 -pipe"
export CONFIG_PROTECT="-*"
export PYTHON_TARGETS="python2_7 python3_6"
export PYTHON_SINGLE_TARGET="python2_7"
export RUBY_TARGETS="ruby23"
export GRUB_PLATFORMS="efi-64 pc"
