subarch: i686
version_stamp: baseos
target: stage3
rel_type: default
profile: default/linux/x86/17.1
snapshot: latest
source_subpath: default/stage2-i686-baseos
portage_confdir: /worksrc/legacyrescuecd-src/portage-etc-x86
portage_overlay: /worksrc/legacyrescuecd-src/portage-overlay
